services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.57.0-noble
    network_mode: host
    depends_on:
      test-data-loader:
        condition: service_completed_successfully
    environment:
      - CI=${CI:-false}
    volumes:
      - ./playwright.config.ts:/test/playwright.config.ts:ro
      - ./${COMPOSE_PROJECT_NAME}/playwright.spec.ts:/test/playwright.spec.ts:ro
    working_dir: /test
    command: bash -c 'npm i @playwright/test@1.57.0 && npx playwright test'
