services:
  ccp-explorer:
    image: samply/ccp-explorer:latest
    ports:
      - 3000:3000
    environment:
      PUBLIC_SPOT_URL: http://localhost:8055

  spot:
    image: samply/rustyspot:latest
    depends_on:
      - proxy1
    ports:
      - 8055:8055
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      BEAM_PROXY_URL: http://host.docker.internal:4001
      BEAM_APP_ID: spot.${DEV_PROXY}.broker.ccp-it.dktk.dkfz.de
      BEAM_SECRET: pass123
      CORS_ORIGIN: http://localhost:3000
      TRANSFORM: LENS
      PROJECT: dktk
      SITES: berlin-test,dresden,essen,frankfurt,freiburg,hannover,mainz,luebeck,muenchen-lmu,muenchen-tum,ulm,wuerzburg,mannheim,hamburg

  proxy1:
    image: samply/beam-proxy:main
    ports:
      - 4001:4001
    environment:
      BIND_ADDR: 0.0.0.0:4001
      BROKER_URL: https://broker.ccp-it.dktk.dkfz.de
      PROXY_ID: ${DEV_PROXY}.broker.ccp-it.dktk.dkfz.de
      PRIVKEY_FILE: /pki/${DEV_PROXY}.priv.pem
      ROOTCERT_FILE: /pki/root.crt.pem
      APP_spot_KEY: pass123
      APP_prism_KEY: pass123
    volumes:
      - ${PKI_PATH}/broker.ccp-it.dktk.dkfz.de:/pki:ro
