services:
  lens:
    image: samply/ccp-explorer:main
    environment:
      PUBLIC_ENVIRONMENT: test

  spot:
    image: samply/rustyspot:main

  blaze:
    image: samply/blaze:latest

  focus:
    image: samply/focus:develop
