services:
  ccp-explorer:
    image: samply/ccp-explorer:latest
    ports:
      - 3000:3000
    environment:
      PUBLIC_SPOT_URL: http://localhost:8055

  spot:
    image: samply/rustyspot:main
    depends_on:
      - proxy1
    ports:
      - 8055:8055
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      BEAM_PROXY_URL: http://host.docker.internal:4001
      BEAM_APP_ID: spot.proxy1.broker
      BEAM_SECRET: pass123
      CORS_ORIGIN: http://localhost:3000
      TRANSFORM: LENS
      PROJECT: dktk
      SITES: proxy2

  focus:
    image: samply/focus:main
    depends_on:
      - proxy2
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      BEAM_PROXY_URL: http://host.docker.internal:4002
      BEAM_APP_ID_LONG: focus.proxy2.broker
      API_KEY: pass123
      ENDPOINT_TYPE: blaze
      BLAZE_URL: http://host.docker.internal:8080/fhir/
      OBFUSCATE: no

  blaze:
    image: samply/blaze:latest
    ports:
      - 8080:8080
    environment:
      ENFORCE_REFERENTIAL_INTEGRITY: false
    healthcheck:
      test: curl -f http://localhost:8080/fhir/metadata
      start_period: 1m

  test-data-loader:
    image: alpine:latest
    depends_on:
      blaze:
        condition: service_healthy
    command: ["sh", "-c", "apk add --no-cache curl && curl https://raw.githubusercontent.com/samply/obds2fhir/refs/heads/develop/src/test/resources/FHIR_oBDS_Expected-File-4.xml | curl -X POST -H 'Content-Type: application/fhir+xml' -d @- http://blaze:8080/fhir"]

include:
  - ../compose.localbeam.yaml
